# Generated by Django 5.0.2 on 2024-03-02 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_plan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('due_date', models.DateTimeField(null=True, verbose_name='dataMn')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_plans', to='customer.customer')),
                ('plan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_plans', to='plan.plan')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
