# Generated by Django 5.0.2 on 2024-03-02 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('plate', models.CharField(max_length=10, verbose_name='placa')),
                ('model', models.CharField(max_length=30, null=True, verbose_name='modelo')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='descricao')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customer.customer')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
