# Generated by Django 5.0.2 on 2024-03-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('description', models.CharField(max_length=50, verbose_name='descricao')),
                ('value', models.FloatField(verbose_name='valor')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
