# Generated by Django 5.0.2 on 2024-03-02 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerVehicle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_vehicles', to='customer.customer')),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_vehicles', to='vehicle.vehicle')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
