# Generated by Django 5.0.2 on 2024-03-02 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('description', models.CharField(max_length=50, verbose_name='descricao')),
                ('max_value', models.FloatField(null=True, verbose_name='valorMax')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Contract_rule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('until', models.IntegerField(verbose_name='until')),
                ('value', models.FloatField(verbose_name='valor')),
                ('contract_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_rules', to='contract.contract')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
