# Generated by Django 5.0.2 on 2024-03-02 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(verbose_name='dataIn')),
            ],
        ),
        migrations.CreateModel(
            name='DateTimeExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_date', models.DateTimeField(verbose_name='dataFn')),
            ],
        ),
        migrations.CreateModel(
            name='Parkmovement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('vehicle_id', models.IntegerField(verbose_name='veiculoID')),
                ('value', models.FloatField(null=True, verbose_name='valor')),
                ('entry_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkmovement_entry', to='parkmovement.datetimeentry')),
                ('exit_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkmovement_exit', to='parkmovement.datetimeexit')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
